### ISSUE TITLE
Illustration 30 #2: replacement image

### ISSUE THREAD

**Issue by happywebdiva** [w3c/EasyChecks#13]
In re illustration 30 (the second of the Keyboard access and visual focus images), in March 2014 Shawn thought it important to replace.  I'm not certain I understand what she wants, but am attaching my best guess.
![focus-highlight-field 2](https://cloud.githubusercontent.com/assets/2060192/10378552/2c57b994-6dcf-11e5-9c8b-61d02965b855.png)
Note that as long as I was editing the image, I balanced the borders. I find this balance less distracting.

**Comment by vuxcaleb** [comment]
@slhenry Does this image match how you envisioned it? 

If so, can you upload this image:
https://cloud.githubusercontent.com/assets/2060192/10378552/2c57b994-6dcf-11e5-9c8b-61d02965b855.png

To:
www.w3.org/WAI/imags/easychecks/keyboard-access-30.png

Then I will make a pull request to the codebase reflecting the updated image.

If not - let me know what it should look like and I will work on an update.

Thanks,
Caleb

**Comment by slhenry** [comment]
Sorry this took me long to reply. I had to go back and figure out the issue. I think it was that the option buttons were poorly placed in <https://www.w3.org/WAI/images/easychecks/focus-highlight-field.png>

So, yeah, that image totally takes care of that issue.

However, there is a *minor* point that "eMail" catches my attention as unusual and awkward. I'm used to "e-mail" or "E-mail" or "Email".

@vuxcaleb are you willing to tweak that, or do you think I should just try to ignore it? ;-)

**Comment by vuxcaleb** [comment]
@slhenry I can update it but do you know what font that is?

**Comment by slhenry** [comment]
probably in the CSS of : https://www.w3.org/WAI/demos/bad/after/survey.html

**Comment by vuxcaleb** [comment]
Illustration is updated and included in pull request for Issue 1.

**Comment by slhenry** [comment]
@vuxcaleb The image in the pull requests has the problem of the option buttons in the wrong place -- which is what AB fixed in the illustration at the top of this thread.

**Comment by vuxcaleb** [comment]
@slhenry sorry! I can fix that tonight and make a new pull request. Good catch!

**Comment by vuxcaleb** [comment]
@slhenry Updated and pull request made. Please merge when you get a chance - thanks!

**Comment by slhenry** [comment]
done!
