### ISSUE TITLE
Images with bad alt?

### ISSUE THREAD

**Issue by nitedog** [w3c/EasyChecks#19]
In looking at issue #18 it occurred to me that most of these missing images have alt="", which seems incorrect to me - I think they are mostly informative images (icons that indicate some information, not pure decoration).

**Comment by vuxcaleb** [comment]
I also noticed that but it seems to be intentional because of the figure description below each image - which would be the same content as alt.

@nitedog I have never seen this approach (empty alt with figure copy below the image) before - is it accessible or should we add the alt content?

**Comment by nitedog** [comment]
@vuxcaleb, I think you mean this code:

> &lt;div class="figure" style="width:676px"&gt; &lt;img src="/WAI/images/easychecks/page-title-tab-popup.png" alt="" width="674" height="110" /&gt;
>   &lt;div class="figcaption"&gt;Figure: Page title in popup, displayed with mouse hover over tab.&lt;/div&gt;
> &lt;/div&gt;

I think it is ok to have the image without an alt-text in this case, but I'm not sure if the relationship between the image and the caption is "programtically determined" (SC 1.3.1). I think it would be better to use a different technique - maybe just the &lt;figure&gt; element but not sure how supported it is.

But what I meant were images like this one:

> To check for missing alt: Look for the red alt icon (&lt;img src="http://wave.webaim.org/img/icons/alt_missing.png" alt="" /&gt;), or search for the alt text &quot;ERROR: Missing alt text&quot;. If you find it, that means the following image is missing alt.

I think in this case it is important to use the same alt-text for the image as the one that appears in the tool, so that people can recognize the image. It may seem redundant because the text says "red alt icon" but the text is actually introducing an icon that people need to be able to find again.

**Comment by vuxcaleb** [comment]
Updates made to code and pull request made.

**Comment by slhenry** [comment]
closed per https://github.com/w3c/EasyChecks/pull/21
