### ISSUE TITLE
Illustrations work needed

### ISSUE THREAD

**Issue by happywebdiva** [w3c/EasyChecks#2]
This is feedback emailed to Sharron, Eric, Shawn, Shadi on Sept. 8.  I have not heard back from anyone, so am transferring this to a place it's less likely to get lost.  (The illustration numbers refer to the table at the end of https://www.w3.org/WAI/EO/wiki/Easy_Checks_-_Illustrations.)

Three items of feedback so far.

1. The github version that I'm seeing (which may be a bit broken) does not have expand / collapse buttons.  IMO this is an improvement -- especially when looking at illustrations on smaller screens.  So hopefully that's something that is in the works.  Is it a change that's being planned for?

2. Illustration #18 - Contrast Ratio (E "To check contrast with IE WAT")
My memory (backed to some extent by the illustrations wiki) is that we had agreed not to use that illustration at all.  It looks bad (distorted by squishing) in the live version on a smaller screen -- but fine in the GitHub draft.  That said I still think it's a wasted use of illustration.  There are other more complicated, less IE-centric things that aren't illustrated and could use illustrations more.  It's a question of priorities and balance -- and this is the kind of thing we worked through as a team -- so we would illustrate what most needed it, but not everything.

3. Illustration #20 - Resize text - Group of three images showing (1) normal-size text, (2) larger text re-wrapping to fit the width, (3) larger text creating horizontal scrolling.
These were supposed to not stack in most browsers at full width but they are in live as well as draft (that's in Chrome on a Mac).  I still have the code in my sandbox.  Eric -- do you want me to dig back through my old code and let you know what's gone awry with this illustration?

**Comment by slhenry** [comment]
Thanks, Anna Belle, for putting this here so everyone can see it and comment. :-)

1. expand / collapse buttons are just not working in the GitHub version. There is no plan to remove them. We wouldn't want people to have to wade past lots of info that doesn't apply to them, e.g., if they are using one toolbar and not the other.

2. Illustration #18 -- I'm fine with not including it.

3. Illustration #20 -- thanks for continuing to work on this!

**Comment by happywebdiva** [comment]
In re. Illustration #20, I've figured out the problem.  I'm opening a separate issue for it.

**Comment by vuxcaleb** [comment]
@slhenry  Updates made to code and pull request made.

**Comment by slhenry** [comment]
closed per https://github.com/w3c/EasyChecks/pull/22
