### ISSUE TITLE
Options for Moving, Flashing, or Blinking Content

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#27]
<p>The new checks for Moving, Flashing, or Blinking Content that we have been working on (<a href="https://github.com/w3c/EasyChecks/issues/1">1</a>, <a href="https://github.com/w3c/EasyChecks/issues/23">23</a>) have been integrated into a draft of the document so we can review them in context. <strong>Please skim the <a href="https://www.w3.org/WAI/eval/preliminary">Easy Checks document</a> overall to re-familiarize yourself with how the other topics and checks are presented.</strong></p>
<p>Two options are presented, A &amp; B below:</p>
<ul>
  <li>A. Two separate topics:
    <ul>
      <li><a href="https://rawgit.com/vuxcaleb/EasyChecks/5ce56f4bb3b5e6f990f3695ea27a4b0641038e78/index.html#flash">Flashing or Blinking Content</a></li>
      <li><a href="https://rawgit.com/vuxcaleb/EasyChecks/5ce56f4bb3b5e6f990f3695ea27a4b0641038e78/index.html#moving">Moving Content</a></li>
    </ul>
  </li>
  <li>B. One combined topic:
    <ul>
      <li><a href="http://w3c.github.io/EasyChecks/index.html#moving">Moving, Flashing, or Blinking Content</a></li>
    </ul>
  </li>
</ul>

**Comment by slhenry** [comment]
[medium-mild] Preference: Option B. One combined topic.

Rationale: I think reviewers will easily check all of these at the same time, rather than wanting to split it out into separate checks. Also, I think flashing is not a highly prevalent accessibility barriers that fully warrants it's own check. The topics are very related and the content that we have for each is very short (in comparison to the other topics) - and somewhat repetitive when split into two separate topics.

**Comment by susanatx** [comment]
My initial thought is to separate them as I think it's important for people to know they are different types of content. But looking at the structure of the resource overall I don't think having them separate is a good fit.

Could we make it visually more clear that the "Moving" piece and "F/B" piece are separate? I know from experience this hard for some people to parse out the differences between the two so this is kind of a word soup that may not help.

**Comment by slhenry** [comment]
@susanatx I updated it with subheadings. I think it looks nice -- however, I had some concern that readers might not understand that flashing and blinking also has the same problems as are listed under moving. So I added:

> In addition to the problems above, 

That adds a bit more complexity, but maybe worth it .

Another idea would be to add flashing and or blinking examples to the first sentence:

> Moving content includes carousels (example carousel), ads, videos, auto-updating stock tickers, and more.

and then we don't need "In addition to the problems above, "

**Comment by slhenry** [comment]
Brent's comments from [survey](https://www.w3.org/2002/09/wbs/35532/28oct/results#xec)
> Replace: Some people have trouble tracking moving objects.
> Replace with: Some people have difficulty tracking moving objects.

Done.

> Replace: Moving content includes "carousels" such as below, videos, ads, auto-updating stock tickers, and more. Users need to be able to control moving content, especially some people with attention deficit or visual processing disorders.
> Replace with: Users need to be able to control moving content, especially some people with attention deficit or visual processing disorders. Moving content includes carousels (example below), videos, ads, auto-updating stock tickers, and more.

In many of the checks -- especially the first few, we first explain what it is, and then the accessibility issue. For this topic, I feel that it would be good to explain what is meant by moving content first -- so people can more quickly understand the breadth of that this topic cover and if it applies to their page.

I don't feel super strongly about that and if the group overall wants to switch the order of the sentences, I'd be OK with that.

**Comment by iamjolly** [comment]
My preference is B. One combined topic. This information seems to be easy enough to parse together in a section rather than having separate sections or checks that testers may need to recall when testing.

**Comment by nitedog** [comment]
I also slightly favor one combined approach.

**Comment by susanatx** [comment]
This looks good @slhenry

**Comment by James-Green** [comment]
i also favor one combined approach

**Comment by dboudreau** [comment]
Also leaning towards a combined approach.

**Comment by vuxcaleb** [comment]
Resolution approved to combine.

**Comment by slhenry** [comment]
https://www.w3.org/2016/11/04-eo-minutes.html#resolution02
