### ISSUE TITLE
use of the word "click" through Easy Checks

### ISSUE THREAD

**Issue by davidberman** [w3c/EasyChecks#3]
We should vanquish this word unless specifically discussing pointing devices that have a button. 
I suggest we use the word "select" instead.

**Comment by slhenry** [comment]
When we discussed this ages ago -- including a couple screen reader users -- it was decided that "click" was more clear, even for people who don't actually click with a mouse, because that's what they are used to in instructions. (It's in minutes somewhere, but I'm not up for digging it up right now.)

I recently worked with documents that use "select" instead of "click" (from http://adod.idrc.ocad.ca/) and it was a bit awkward to me -- even though I'm smart and totally know what it meant, it still required a tad more cognitive processing.

[medium] So I'd vote for leaving "click"; although I don't feel super strong about it at this point.

**Comment by gheake-1** [comment]
I understand what David is saying but would have to agree with Shawn  The concept of click withing computer/technology literacy I think is universal and easily understood. 
[medium] I too would vote for leaving "click".

**Comment by bakkenb** [comment]
After reading through some of the Easy Checks content, in my opinion I would recommend staying with the word "click". There are other instances where the word "select" is also used in the same bulleted list of directions. Click was for buttons or links and select was being used for check boxes and radio buttons and such. I also believe that this concept is universally known and applied widely.

**Comment by hkramer** [comment]
I would agree with the consensus above - staying with "click." I think "select" is not as clear.

**Comment by davidberman** [comment]
Hmmm... so then let's brainstorm a word that is better than "select" and more appropriate for this decade of touch and mobile devices... as well as a host of assistive devices.

**Comment by slhenry** [comment]
closing based on input so far. re-open if warranted, e.g., if have concrete suggestions that take into account perspectives above.

**Comment by davidberman** [comment]
If I'm truly alone on this, I'll drop it. However I feel strongly about it, so allow me a more thorough appeal...

* priority: [strong]
* location: all instances of "click" that are not referring to mouse-specific issues
* current wording/code: "click"
* suggested revision: "select"
* rationale:
I realize that keyboard-only and touch users are accustomed to putting up with the inaccuracy of "click".
However, as we are in the business of providing clarity and guidance on technical issues, we should show leadership in this area of language. Words are the dress of thoughts, and to resign ourselves to the convenience of the status quo is to absolve our responsibility to affect change.

And I am aware that our community has correctly and collectively broadened the meaning of words such as "see" or "view" to include interpretations that don't require sight. However, I'd like to argue that "click" doesn't fall into that category.

You may be able to find a more fitting parallel example, however the first that jumps to mind for me is how the norm in legal documents not so long ago was to use the word "he" to refer to everyone. Next came a movement to the more accurate and inclusive "He/she" or "She or he". I recall how awkward and unnecessarily pernickity this initially seemed to many. Today, of course, it doesn't seem odd at all... while writers quickly found ways to more elegantly include all genders. So, let's reserve "click" for when we're providing guidance or examples that are truly about clicking, while getting ahead of the important nuances of addressing tapping, touch, and the very necessary need to find accessible, delightful alternatives for all nature of gesture interface.
