### ISSUE TITLE
link & markup fixes

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#30]
https://validator.w3.org/checklink?url=https://www.w3.org/WAI/eval/preliminary

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.w3.org%2FWAI%2Feval%2Fpreliminary

**Comment by vuxcaleb** [comment]
@slhenry Updated and pull request made. Please merge when you get a chance - thanks!

**Comment by slhenry** [comment]
Thanks @vuxcaleb 
I merged. Result is at <https://w3c.github.io/EasyChecks/>

There are a few more validation warnings that would be good to clean up: <https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2FEasyChecks%2F>

Also, where you took out shape, there's extra spaces that would be nice to clean up, e.g.,
>  a href="#toc"  >

And the microsoft link edit didn't work, and there are more links that could be cleaned up: 

https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2FEasyChecks%2F&hide_type=all&depth=&check=Check

**Comment by vuxcaleb** [comment]
Working on the changes look out for a pull request soon.

**Comment by slhenry** [comment]
done!
