### ISSUE TITLE
Check the illustration table to confirm all done

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#31]

**Comment by yatil** [comment]
Link to the illustration table: https://www.w3.org/WAI/EO/wiki/Easy_Checks_-_Illustrations#table

Some of those are minor, some might be covered by #33. Let’s have the open illustrations as individual issues here – than we can triage if there are illustrations that we _need_ to update **now** or that can be changed in the next weeks. I think the changes are largely inessential.

**Comment by slhenry** [comment]
done!

most are done -- some we just commented out as they are low priority
