### ISSUE TITLE
Add the github box to easy checks before publishing

### ISSUE THREAD

**Issue by yatil** [w3c/EasyChecks#32]
Just for reminding me :-)

**Comment by slhenry** [comment]
I put the HTML there, but not the CSS yet - pending input from @yatil (and @nitedog if he wants) on this question:

> Is there any reason not to put the contribute CSS in wai-main.css?

**Comment by yatil** [comment]
It's easy-checks specific CSS, so it makes sense to have it in the document until we know we want to use it on other pages in the future. Also that way it's preserved for when we are applying the redesign. But it doesn't matter to much, tbh.

**Comment by slhenry** [comment]
/me not understanding, especially "easy-checks specific CSS"

The contribute CSS is used on several pages throughout the WAI website. Isn't it the same for all of them? Why not have that CSS in the main style sheet so we don't have to have it in every doc that uses it?

Not sure what I am missing...

**Comment by yatil** [comment]
Sorry, I was confused and mixed things up. Yes, we can add that CSS to the main CSS file.

**Comment by slhenry** [comment]
I think I got this all done. @yatil - wanna do a quick QA check? :-)
