### ISSUE TITLE
Check issues from Completion Plan

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#35]
Review the [Completion Plan wiki page](https://www.w3.org/WAI/EO/wiki/Easy_Checks#Completion_Plan) to make sure that everything is either already done, or add it as an Issue in GitHub. And update the Completion Plan wiki so each issue shows with either [done] or [GitHub Issue].

**Comment by vuxcaleb** [comment]
@slhenry Updated and pull request made. Please merge when you get a chance - thanks!

**Comment by slhenry** [comment]
merged. (still need to check & update wiki page, afaik :-)

**Comment by slhenry** [comment]
Robert Jolly and Sharron Rush taking on task!

**Comment by slhenry** [comment]
Sharron: "Done."
