### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#37]
A while ago there was some strong opinion that we need to have clearer disclaimers on Easy Checks. We have the following [open issue](https://www.w3.org/WAI/EO/wiki/Easy_Checks#To_Do):

> [Sharron updating] disclaimer — Add note about not definitive at the bottom of each section, per Suggested: More visible, stronger this is not definitive, have to do more... below. Need to finalize wording and visual appearance.

Discussion of this is at https://www.w3.org/WAI/EO/wiki/Easy_Checks#Suggested:_More_visible.2C_stronger_this_is_not_definitive.2C_have_to_do_more...

@vuxcaleb Caleb took a pass at implementing what he thought was the conclusion from that discussion. It is implemented [in this draft after the TOC](https://w3c.github.io/EasyChecks/#toc).

**Please scroll up to see it in context** - and also follow the link in it.

EOWG feedback encouraged...

_(/me has opinions but will wait to share them until others have a chance to chime in :-)_

**Comment by slhenry** [comment]
Discussed in eo-plan on 8 Dec. Summary coming...

**Comment by slhenry** [comment]
Judy feels still needed. She thought presentation(s) at and participants of [The ICT Accessibility Testing Symposium](http://ictaccessibilitytesting.org/) feel this is still an issue.

(/me looked through [proceedings ](http://ictaccessibilitytesting.org/docs/Proceedings%20of%20the%202016%20ICT%20Accessibility%20Testing%20Symposium.pdf) and found: "the authors are careful to mention that passing these simple tests does not mean that a page is accessible." Guess other stuff was said. ;-)

**Comment by slhenry** [comment]
Thoughts:
* It feels *so* repetitive to me -- The first box is so close in wording and location to the second paragraph of the doc/intro, that it seems awkwardly redundant. And linking to the section at the bottom of the doc is awkward and seems unnecessary -- especially since it's essentially the same things said in the second paragraph and the disclaimer with just a little more info. .. but maybe it's good in case people just see this disclaimer and not read the intro. *sigh*
* We're using color to draw attention to it. Should probably add "Important:" for non-visual users.

Straw proposal to limit redundancy and awkwardness, while still adding another layer of "disclaimer":
* put the box right under "Using these Easy Checks"
* keep the visual presentation as is
* use succinct clear wording:
> Important: These checks are not definitive and not comprehensive. More robust evaluation is needed to identify all potential accessibility issues. (More info is under [Encourage thorough accessibility evaluation](https://www.w3.org/WAI/eval/preliminary#moreeval).)

* or maybe even just:
> Important: These checks are not definitive and not comprehensive. More info is under [Encourage thorough accessibility evaluation](https://www.w3.org/WAI/eval/preliminary#moreeval).

**Comment by bakkenb** [comment]
Good suggestions Shawn. I agree with them.

[mild-medium] I prefer the first (a bit longer) straw proposal wording because it tells them why it is not definitive or comprehensive.

**Comment by vuxcaleb** [comment]
+1

**Comment by slhenry** [comment]
another minor edit that might help overall: https://github.com/w3c/EasyChecks/pull/38

**Comment by slhenry** [comment]
proposed solution implemented [in draft](https://w3c.github.io/EasyChecks/#domore)

**Comment by slhenry** [comment]
[EOWG telecon discussion 9 Dec](https://www.w3.org/2016/12/09-eo-minutes.html#item03)
