### ISSUE TITLE
Functionality deleted? for hide/show sections of content

### ISSUE THREAD

**Issue by lakeen** [w3c/EasyChecks#44]
I am reviewing the document in Chrome and Firefox and I'm not getting [+] or the ability to hide sections.  Has this functionality been deleted or to be added in the latest version?

Click headings with [+] buttons to get hidden information

Some sections of this page might not apply to your situation, for example, they are for a browser you don't have, or you only need to read them once. These sections are hidden by default so they don't clutter the page. You can expand them to see the information. The headings of hidden sections have a plus button [+] before them. Screen readers will say something like: "graphic, expand this section". To get the hidden information, click the button or click anywhere on the heading.

The sections below all have hidden information under expandable headings. The first time you read this page, we recommend that you expand the headings of these five sections and read them.

**Comment by lakeen** [comment]
If we are deleting the hide/show [+] then the images under "Heading Checks" should also be updated.

**Comment by yatil** [comment]
Hi Laura.

The Expand/Collapse functionality is not working on the GitHub preview for now, the JavaScript is quite interesting. When copied over to the W3C server, the Expand/Collapse will work properly.

**Comment by slhenry** [comment]
Thanks for careful review to see that, Laura.
