### ISSUE TITLE
Illustrations: Check Text Wrapping

### ISSUE THREAD

**Issue by yatil** [w3c/EasyChecks#46]
Reminder for myself. I should be able to look into it on Wednesday (December 14, 2016).

**Comment by slhenry** [comment]
Related: https://github.com/w3c/EasyChecks/commit/8e655117fbb76e3cab2f17f820c27eff30db4e28

**Comment by yatil** [comment]
I really hope this works now, @slhenry.

**Comment by slhenry** [comment]
It does!
