### ISSUE TITLE
[Easy Checks] Typo

### ISSUE THREAD

**Issue by susanatx** [w3c/EasyChecks#51]
This is a comment related to [Easy Checks - A First Review of Web Accessibility](https://www.w3.org/WAI/eval/preliminary)

priority: Important
location: "Keyboard instructions: Ctrl for Windows, cmd for Mac" section
current wording: Some of the keyboard instructions are different for Windows and Mac; for example, "Ctrl" verses "cmd" 
suggested revision: Some of the keyboard instructions are different for Windows and Mac; for example, "Ctrl" **versus** "cmd" in:
rationale: wrong word

**Comment by slhenry** [comment]
but "verses" is more poetic (pun from previous telecon discussion ;-)

fixed. thanks for the catch!
