### ISSUE TITLE
[Easy Checks] - toolbar availability

### ISSUE THREAD

**Issue by AndrewArch** [w3c/EasyChecks#54]
This is a comment related to [Easy Checks - A First Review of Web Accessibility](https://www.w3.org/WAI/eval/preliminary)

[medium] In https://w3c.github.io/EasyChecks/#using we only refer to using Chris Pederick's toolbar in Firefox. While we talk about Firefox in all the examples, the toolbar is also available in Chrome and Safari and the approaches described work equally well. As such I strongly recommend (soon if not now) that we add a link to https://chrispederick.com/work/web-developer/ where all versions are listed and can be download for any of these three browsers, _and_ add some words that the techniques apply to the use of the web developers toolbar in any of these browsers too.

Editor's discretion for now or later

**Comment by yatil** [comment]
Strong +1 for the 2017 Update :-)

**Comment by slhenry** [comment]
ummm - I am sooo tempted to do that now, not to wait. It's a tedious change, but not really a significant one in terms of rewriting much content.

I see Download for Chrome, Firefox, Opera. Is it not giving me Safari just 'cause I'm on Windows? Does it give those on Mac Download for Safari?

**Comment by yatil** [comment]
It’s not available for Safari, but that is fine, Mac people are usually using more than just Safari afaik. 

(This is the only Safari extension I know: http://pauljadam.com/extension.html)

Happy to make the change for Chrome, FF, Opera now and then add another way to do it in Safari later, if really necessary.

**Comment by slhenry** [comment]
I made the change. (I meant to do it on a separate branch for people to review before committing it, but I messed up. :(

EOWG: All OK with that change? Any concerns? Will someone QA it?

**Comment by yatil** [comment]
Hi Shawn, I quickly skimmed, looks good, but I found a typo (see PR #58)

**Comment by sharronrush** [comment]
Yes agreed to the change , thanks for catching the typo

**Comment by bakkenb** [comment]
+1 to the change.
