### ISSUE TITLE
Background section: clarity of third sentence

### ISSUE THREAD

**Issue by iamjolly** [w3c/EasyChecks#59]
moved the following into this issue from the wiki page:

> that the third sentence under "Background" could be clearer. Currently: To check a couple details, you need to see the visual page or hear audio. Suggest: To perform a couple of the checks, you need to see the visual page or hear audio. {Bim}

**Comment by bakkenb** [comment]
+1 to the suggested edit. Sounds better than "check a couple details."

**Comment by slhenry** [comment]
Current wording was: "To check a couple of details, it may be necessary to see the visual page or hear audio." (I'm not sure where that come from.) In this context: "These checks are designed for anyone who can use the web. You don't need much knowledge or skill. To check a couple of details, it may be necessary to see the visual page or hear audio. However, there are many things that anyone can check."

Changed to: "Some of the checks require seeing the web page or hearing the audio."

Rationale: Trying to word it as "delicately" as possible - even if a little less direct I think it's worth it.
