### ISSUE TITLE
[Easy Checks] Alt for search button

### ISSUE THREAD

**Issue by sharronrush** [w3c/EasyChecks#60]
How was this discussion between Eric and Shawn resolved?

- (For  example, appropriate text alternative for a search button (search) would be "search", not "magnifying glass".) 
- This text is copied and pasted from the page and the magnifying glass is replaced with the alt text “search”, but it should read “magnifying glass” – even better would be a button with a magnifying glass and the alt text “button with magnifying glass”. {Eric}

**Comment by slhenry** [comment]
I think we decided not to have alt on this image because it would add confusion. Also, I think adding "button" would just add a little unnecessary complexity to the point.

@yatil - feel free to re-open if you disagree. :-)

**Comment by yatil** [comment]
Good for me.
