### ISSUE TITLE
Title bar in Firefox on Mac

### ISSUE THREAD

**Issue by yatil** [w3c/EasyChecks#61]
https://www.w3.org/WAI/EO/wiki/Easy_Checks#e1

Firefox still has no title bar on MacOS and will likely never get one, so my proposal is to change

> Firefox: If the title bar isn't displayed you might be able to display it by pressing: Alt+V, T, M (or right-mouse click in the empty area after the tab and select Menu Bar).

to

> Firefox, on Windows: If the title bar isn't displayed you might be able to display it by pressing: Alt+V, T, M (or right-mouse click in the empty area after the tab and select Menu Bar).

Then this is resolved in my view.

**Comment by slhenry** [comment]
thanks. done.
