### ISSUE TITLE
[Easy Checks] Line break needed after Images + Numbered lists issue

### ISSUE THREAD

**Issue by HerinHentry** [w3c/EasyChecks#65]
No line breaks after images. Hence the bulleted lists are not aligned well. Issue happens in Chrome 55, Firefox 45, IE 11 - Tested on Windows 7 laptop

![easy checks](https://cloud.githubusercontent.com/assets/15111528/21309993/90d6d8d2-c634-11e6-9afa-386c4b4e3c77.PNG)

**Comment by yatil** [comment]
Thanks, I’ll fix this.

**Comment by slhenry** [comment]
I just noticed that there is not enough space between the bottom of images and the text below them. Let me know if you need a screen capture...

**Comment by yatil** [comment]
Please attach a screenshot & browser info. that would be helpful.

**Comment by slhenry** [comment]
I'm getting the same issue in Chrome, Firefox, and IE.
![spacing](https://cloud.githubusercontent.com/assets/6991814/22045908/df484860-dce2-11e6-9f5e-3a4f7d3942c9.png)

**Comment by yatil** [comment]
Hi @HerinHentry and @slhenry, I _think_ I have fixed the issue, can you double check? http://w3c.github.io/EasyChecks/

@slhenry I think the issue you described was addressed by the new figure code, however I found it to be clearer if the three use cases there were in a list. to underscore the relationship. I added the list in e4bcd7f. Feel free to roll back, if it is not appropriate.

**Comment by HerinHentry** [comment]
@yatil Yes, it looks good now. Snapshot of one image below for reference.

![image](https://cloud.githubusercontent.com/assets/15111528/23016648/61778b2e-f48b-11e6-879c-bf8991c13cc1.png)

Thanks
