### ISSUE TITLE
[Easy Checks] - Contrast ratio ("color contrast") - Ambiguity (Normal size)

### ISSUE THREAD

**Issue by HerinHentry** [w3c/EasyChecks#66]
In the What to check for section, the below statement seems a bit ambiguous:
Web pages should also have a minimum contrast by default: a contrast ratio of at least 4.5:1 for normal-size text.

CSS font-size property supports the below font sizes:
font-size: medium | xx-small | x-small | small | large | x-large | xx-large | smaller | larger | length | initial | inherit;

Browsers support : Very small | smaller | medium | large | very large

I think we need to be a bit more clear here as some websites uses 10pts, some uses 12pts.

![normal size font](https://cloud.githubusercontent.com/assets/15111528/21311878/94c3d6a8-c63d-11e6-9949-1dc88bda2f1b.PNG)

**Comment by yatil** [comment]
I agree this could be more specific, it is 4.5:1 for font sizes below 24px (18pt), or below 18.5px (14pt) when bold.

**Comment by slhenry** [comment]
_Proposed revised wording:_

Web pages should also have a minimum contrast by default &mdash; a contrast ratio of at least:
* 4.5:1 for text that is smaller than 18pt (24px) normal, or 14pt (8.5px) bold
* 3:1 for [larger text](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast#larger-scaledef)

**Comment by slhenry** [comment]
Discussed in [13 Jan telecon](https://www.w3.org/2017/01/13-eo-minutes.html#item03) and put on weekly [survey](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-13-Jan-2017/results#xq1) for approval of resolutions.
