### ISSUE TITLE
[Easy Checks] - Text Resize

### ISSUE THREAD

**Issue by HerinHentry** [w3c/EasyChecks#67]
Another reason all texts do not resize is because of the use of mix of font-size measures (both absolute and relative font-size) in the same page. Only relative fonts can be resized using browsers text resize. Others need assistive technology or browser zoom.

Absolute font sizes:
mm | cm | in | pt | pc | px

Relative font sizes:
em | % | ex | named font-size

![text resize](https://cloud.githubusercontent.com/assets/15111528/21312339/8db69dc6-c63f-11e6-8f61-f20772a115ef.PNG)

**Comment by yatil** [comment]
Absolute font sizes are zoomed in most (if not all) browsers, I tested in Firefox, with text-only zoom on and off. Here is a test:

http://codepen.io/yatil/full/bgNeNL/

**Comment by HerinHentry** [comment]
When we change the Font size in Chrome using Settings > Web Content > font-size this does not work. Also, WCAG 1.4.4 talks about Resize Text. I think this is more of a Chrome issue with absolute font sizes.

But, still as per 1.4.4 : 
Authors may satisfy this Success Criterion by verifying that content does not interfere with user agent support for resizing text, including text-based controls, or by providing direct support for resizing text or changing the layout.

**Comment by slhenry** [comment]
Ah, yes, this is still a complicated issue with browser support, etc. :-(

In Easy Checks, we've tried to avoid contentious, complex issues. ([Criteria for checks](url).) In this case, "(A common problem is that text is not provided as actual text format but instead the text is in an image. Text in images does not get larger when users increase text size.)" is intended to just be one example, not comprehensive listing of all issues.

As absolute and relative font-size is more complicated, I **propose that we leave the wording as is and do not add anything in Easy Checks about that.**

**Comment by slhenry** [comment]
Discussed in [13 Jan telecon](https://www.w3.org/2017/01/13-eo-minutes.html#item03) and put on weekly [survey](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-13-Jan-2017/results#xq1) for approval of resolutions.
