### ISSUE TITLE
[Easy Checks] - Contrast ratio - Text + Images of text

### ISSUE THREAD

**Issue by HerinHentry** [w3c/EasyChecks#68]
Currently Contrast ratio is listed under the easy checks for Text. It might be overlooked as Contrast ratio does not apply to images / infographics.

I think we need to include a line to include images as
The visual presentation of text and images of text has a contrast ratio of at least 4.5:1 as stated in [1.4.3 Contrast (minimum)
](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast)

![contrast ratio infogrpahics](https://cloud.githubusercontent.com/assets/15111528/21312846/97c5cdb6-c642-11e6-8956-a5b622d5415d.PNG)

**Comment by slhenry** [comment]
_Proposed revised text:_

> Text and background should also have a minimum contrast by default...

(I think we want to keep it simple and not add "images of text".)

**Comment by slhenry** [comment]
Thanks for ideas in [13 Jan telecon](https://www.w3.org/2017/01/13-eo-minutes.html#item03), which included:
> All text should provide at least minimum contrast between text and its background by default

&mdash; based in part from [Understanding ](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast) wording:
> provide enough contrast between text and its background

After working on it more, I propose splitting up the point into separate sentences to make them more clear and simple:

> _[[existing text](https://www.w3.org/WAI/eval/preliminary#contrast) about user needs and changing colors.]_<br/>
> There should also be sufficient contrast between text and its background by default, so that many people can read it without changing the colors.<br/>
> _[(parenthetical comment about terminology.)]_<br/>
> **What to check for:**
The contrast between all text and its background is at least:

**Comment by bakkenb** [comment]
+1 to @slhenry recommendation

**Comment by hkramer** [comment]
+1 to @slhenry recommendation

**Comment by slhenry** [comment]
implemented
