### ISSUE TITLE
maybe pre-launch - text edit under "Multimedia (video, audio) alternatives"

### ISSUE THREAD

**Issue by lakeen** [w3c/EasyChecks#78]
Under Multimedia (video, audio) alternatives > Captions
Automatic captions are not sufficient for accessibility because they are not accurate enough. For example, in YouTube, if only "automatic captions" are listed **(as in the image above)**, there are no sufficient captions and the video is not accessible. Captions in the specific language need to be listed. [@@ say more ?] – Image is below the text.

image is below not above

**Comment by slhenry** [comment]
humm... I cannot find that and the @@ looks like it's from an older version. Strange. Can you check what URI you're looking at? If https://www.w3.org/WAI/eval/preliminary
please try a hard refresh...

**Comment by lakeen** [comment]
This was a paste error on my part. I am responding to the bold text: 

change:  (as in the image above)

to:  (as in the image below)

Looks like you removed (as in the image above)
