### ISSUE TITLE
How best to work on the illustrations?

### ISSUE THREAD

**Issue by happywebdiva** [w3c/EasyChecks#8]
All of the illustrations need careful review.  With the last update of Easy Checks live that involved illustrations, some issues fell between the cracks.  That was 1.5 years ago.  I can go back through my notes illustration by illustration, but before I invest that kind of time, I would like some sort of methodology in place.  

Doing a table that tracked them was great, but doing it in the Wiki was crazy-making.  Can we use a shared Google Drive spreadsheet?  Or is there some other reasonably easy way to keep track of who has reviewed what and the status of each illustration?

Thanks

**Comment by happywebdiva** [comment]
I notice for the "work for this week" (update 10/2) that it says "Easy Checks - Published version, Updated draft in GitHub - ideally complete by Wednesday 7 Oct. It's been a nearly complete draft for several months. We want to clean up the remaining issues and get it out of Draft status. We don't have an editor to make any significant non-essential changes now, and can record those updates for later when we do."

I am concerned that none of the details under work for this week address the illustrations issues.  Easy Checks has waited this long to get out of draft status so IMO it can wait a few weeks more until the illustrations get something approximating the kind of attention written content does.

HIghest priority IMO is this open issue -- #8 -- a place or way to track what needs to happen with each illustration.  Is there some easy way to do this on GitHub?  E.g. I could have the spreadsheet on my computer and each time I update it, attach a PDF of the file to an open issue about illustrations.

**Comment by slhenry** [comment]
Hi Anna Belle,

I apprecaite your continued attention to the illustrations.
...
> I am concerned that none of the details under work for this week address the illustrations issues. Easy Checks has waited this long to get out of draft status so IMO it can wait a few weeks more until the illustrations get something approximating the kind of attention written content does.

Rest assured the illustrations will get their due attention before the doc is finalized. :-)

I wasn't aware that there were actions for all of EOWG to do this week regarding the illustrations -- but Sharron has been managing this project recently, so maybe she knows something I don't. She was on vacation so I put together the Work for this Week without her. She can add anything y'all figure out that all of EOWG needs to do at this point.

For now, I added to the Work for this Week: "fyi, polishing illustrations is still in progress". I hope that gives you sufficient reassurance that the illustrations are not being forgotten.

> HIghest priority IMO is this open issue -- #8 <https://github.com/w3c/EasyChecks/issues/8> -- a place or way to track what needs to happen with each illustration. Is there some easy way to do this on GitHub? E.g. I could have the spreadsheet on my computer and each time I update it, attach a PDF of the file to an open issue about illustrations.

ftr, the previous table for managing open issues on illustrations is at <https://www.w3.org/WAI/EO/wiki/Easy_Checks_-_Illustrations#Illustration_inventory>. That table is in HTML so maybe we continue to update it there? We could put it in HTML in GitHub, although I don't see that that would make it any easier.

Thanks for offering the local spreadsheet and PDF option. Unfortunately the PDF would not be accessible. And also then others couldn't update it without getting you to do it.

Another idea is to make a GitHub issue for each open illustration. From quick skim, it looks like there are less than a dozen. That seems like a good approach -- although maybe I'm missing something? I've added Label for "illustrations" (with bright yellow color :-) that will help us keep track of illustration-related issues in any case.

Best,
~Shawn

**Comment by slhenry** [comment]
> I am concerned that none of the details under work for this week address the illustrations issues. Easy Checks has waited this long to get out of draft status so IMO it can wait a few weeks more until the illustrations get something approximating the kind of attention written content does.

Rest assured the illustrations will get their due attention before the doc is finalized. :-)

I wasn't aware that there were actions for all of EOWG to do this week regarding the illustrations -- but Sharron has been managing this project recently, so maybe she knows something I don't. She was on vacation so I put together the Work for this Week without her. She can add anything y'all figure out that all of EOWG needs to do at this point.

For now, I added to the Work for this Week: "fyi, polishing illustrations is still in progress". I hope that gives you sufficient reassurance that the illustrations are not being forgotten.

> HIghest priority IMO is this open issue -- #8 <https://github.com/w3c/EasyChecks/issues/8> -- a place or way to track what needs to happen with each illustration. Is there some easy way to do this on GitHub? E.g. I could have the spreadsheet on my computer and each time I update it, attach a PDF of the file to an open issue about illustrations.

ftr, the previous table for managing open issues on illustrations is at <https://www.w3.org/WAI/EO/wiki/Easy_Checks_-_Illustrations#Illustration_inventory>. That table is in HTML so maybe we continue to update it there? We could put it in HTML in GitHub, although I don't see that that would make it any easier.

Thanks for offering the local spreadsheet and PDF option. Unfortunately the PDF would not be accessible. And also then others couldn't update it without getting you to do it.

Another idea is to make a GitHub issue for each open illustration. From quick skim, it looks like there are less than a dozen. That seems like a good approach -- although maybe I'm missing something? I've added Label for "illustrations" (with bright yellow color :-) that will help us keep track of illustration-related issues in any case.

**Comment by slhenry** [comment]
Re: I am concerned that none of the details under work for this week address the illustrations issues. Easy Checks has waited this long to get out of draft status so IMO it can wait a few weeks more until the illustrations get something approximating the kind of attention written content does.

Rest assured the illustrations will get their due attention before the doc is finalized. :-)

I wasn't aware that there were actions for all of EOWG to do this week regarding the illustrations -- but Sharron has been managing this project recently, so maybe she knows something I don't. She was on vacation so I put together the Work for this Week without her. She can add anything y'all figure out that all of EOWG needs to do at this point.

For now, I added to the Work for this Week: "fyi, polishing illustrations is still in progress". I hope that gives you sufficient reassurance that the illustrations are not being forgotten.

Re: HIghest priority IMO is this open issue -- #8 <https://github.com/w3c/EasyChecks/issues/8> -- a place or way to track what needs to happen with each illustration. Is there some easy way to do this on GitHub? E.g. I could have the spreadsheet on my computer and each time I update it, attach a PDF of the file to an open issue about illustrations.

ftr, the previous table for managing open issues on illustrations is at <https://www.w3.org/WAI/EO/wiki/Easy_Checks_-_Illustrations#Illustration_inventory>. That table is in HTML so maybe we continue to update it there? We could put it in HTML in GitHub, although I don't see that that would make it any easier.

Thanks for offering the local spreadsheet and PDF option. Unfortunately the PDF would not be accessible. And also then others couldn't update it without getting you to do it.

Another idea is to make a GitHub issue for each open illustration. From quick skim, it looks like there are less than a dozen. That seems like a good approach -- although maybe I'm missing something? I've added Label for "illustrations" (with bright yellow color :-) that will help us keep track of illustration-related issues in any case.

**Comment by happywebdiva** [comment]
Thanks, Shawn!  In re work for this week, that makes sense how this happened and does reassure me.  And thanks for updating that.  

Doing the HTML table in the wiki was enough of a pain that I'm not sure what's in there is the latest update.  (An aside - I can double check that as I do the inventory.)  Sharron has another idea.  More on that front coming soon I expect.

**Comment by vuxcaleb** [comment]
Based on the organization work previously done and the efficiencies it creates we will use a combo of Wiki page with HTML table showing each image numbered, current state, and what needs to happen to make it final with Github issues which reference the image number
    - Wiki: https://www.w3.org/WAI/EO/wiki/Easy_Checks_-_Illustrations#Illustration_inventory

**Comment by slhenry** [comment]
closed as requested by @vuxcaleb
