### ISSUE TITLE
possible "easy edits"

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/EasyChecks#83]
maybe pre-launch
It may possibly freshen the approach and voice of the page and result in simplifying and reducing if some of the "extra" information was removed, such as:
"Some sections of this page might not apply to your situation, for example, they are for a browser you don't have, or you only need to read them once. These sections are hidden by default so they don't clutter the page. You can expand them to see the information. The headings of hidden sections have a plus button [+] before them. Screen readers will say something like: "graphic, expand this section". To get the hidden information, click the button or click anywhere on the heading."

This info seems unnecessary and bogs down the process a bit.

**Comment by slhenry** [comment]
I took another look at this and didn't see any easy tersification without losing content. Closing for now. Feel free to re-open if you have specific edit suggestions. Thanks!
